# Generated by Django 2.2 on 2021-04-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210417_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commondocument',
            name='directory',
        ),
    ]
