# Generated by Django 2.2 on 2021-04-25 02:13

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_commondocument_directory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commondocument',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=core.storage.OverwriteStorage(), upload_to=core.models.get_upload_path),
        ),
    ]
